print("\n\n")
print(" Lista de adjacência do Grafo")
print("\n" )
print(" Vértices |      Vétices adjacentes  ")
print(" ( A ) ---->> ( B ) -->> (D) -->> (K) -->> (N)")
print(" ( A ) ---->> ( B ) -->> (D) -->> (K) -->> (N)")
print(" ( A ) ---->> ( D ) -->> (E) -->> (I) -->> (M)")
print(" ( A ) ---->> ( N ) -->> (B) -->> (O)")
print(" ( A ) ---->> ( K )")
print(" ( B ) ---->> ( C )")
print(" ( B ) ---->> ( N )")
print(" ( I ) ---->> ( J )")
print(" ( I ) ---->> ( D )")
print(" ( I ) ---->> ( H ) -->> (J)")
print(" ( E ) ---->> ( H )")
print(" ( H ) ---->> ( G ) -->> (E) -->> (I)")
print(" ( G ) ---->> ( F ) -->> (H)")
print(" ( F ) ---->> ( E ) -->> (G) -->> (L)")
print(" ( F ) ---->> ( L ) -->> (Q)")
print(" ( B ) ---->> ( A )")
print(" ( E ) ---->> ( D ) -->> (F) -->> (H) -->> (M)")
print(" ( E ) ---->> ( M )")
print(" ( D ) ---->> ( M ) -->> (E) -->> (P)") 
print(" ( N ) ---->> ( O ) -->> (P) -->> (R) -->> (S)")
print(" ( M ) ---->> ( P ) -->> (O) -->> (Q) -->> (R)")
print(" ( L ) ---->> ( Q ) -->> (P) -->> (R)")
print(" ( O ) ---->> ( S ) -->> (T)")
print(" ( S ) ---->> ( T )")
print(" ( O ) ---->> ( R ) -->> (P) -->> (Q)")
print(" ( P ) ---->> ( O )")
print(" ( P ) ---->> ( R )")
print(" ( Q ) ---->> ( P )")
print(" ( R ) ---->> ( Q )")